version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13-management        # latest LTS w/Management UI
    ports:
      - "5672:5672"         # AMQP
      - "15672:15672"       # http://localhost:15672  user/pass: guest/guest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest